# Generated by Django 2.2.6 on 2019-11-27 01:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'cesta',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo_barras', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('cpf', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'vendedor',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('precototal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_pagamento', models.CharField(choices=[('A', 'A vista'), ('P', 'A prazo'), ('C', 'Cartao')], max_length=1)),
                ('cestas', models.ManyToManyField(to='app.Cesta')),
                ('cpf_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='app.Cliente')),
                ('cpf_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vendedor')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.AddField(
            model_name='cesta',
            name='produtos',
            field=models.ManyToManyField(to='app.Produto'),
        ),
    ]
